language: bash
install: chmod u+x test.sh
script: bash test.sh
deploy:
  provider: s3
  bucket: "S3 Bucket"
  skip_cleanup: true
  on:
    branch: main
env:
  global:
  - secure: R9Fp0efIVY68wTd/mFLOoAgQiGwRgdaoNYT+7sivNskyq6y+cbdhbBkk6fERpi5j2XKCjcHIAF83XBgishw9TzsSE6UxO7FeOCZnJvYb8mIZnW6eVKNRfj0F/vlG7clnPVAPi+Jnnv6zZ0ENu50LMW0Yj87p/kCgqVc/HlhzNjHTiCN77WQOHet96Xuo2UJpYE8engM+nVRRcQ3OE71oQuMfdpxXrPntvwQP6ghDiyNL1v5JU+Z0Ee4qbozrF8dlR6ZT0PoXJsi9lFZreIgiaHXzZjvxribRppHgvJhQbEnQ6mPQjc5YqorTrc2fNlx/hDDE7Y5qQwp6n0VqQFg5gRYyKpVZCRhFTkk2zREqitOVlYcqjnK9iZylUYCKXD43IJUbFD/W48R2dRSmNPzobbFXH95m5p271inSPTaxIJPsZ8ZKSN5OVGYhfkJP0HQd/HKpDF3rqV6tWA7ZMaXvltA4tUSEbgVJ4zsrDpmFDDsKJZ9klWSAhI7etni4K76l+y8N8z2m65/Iq9t0CEzwBcuhvs+uiPcC2dHFlfuZyf9LioTavo3stOzppEfYx4v0WXnfxthJFFfJsC042sWy8hCxkY1lQ0bwcAkF4/rEaDj8fdTRuQJpoaDdc7L4c3+cm16hDCNG8WZ0w1ItbfJyrf25eUyUNv6yHiiCURXS+SQ=
  - secure: df4HP8Xon32u0PKF4WBIVoI5t+14p07cMzWjpBYJ+EMpVt6Vzs1Cp4oT3XNUU02YHisVg7VhjUhSyW4vEH7VmlO42q0lDzWxamt2YZq5EEbouRjM/tZgbUcDqSkGT9kWqmLgyTCic6PZvy6gA3ft5FrcchTaWwbcjB5KJIpFG0VcuWnnUkFig84s94ElLcdVrFlLFz+qdu5Kdh1vqvmBKWEd0jWykTrHgl9wVGfIQPAUhx08Qv2HxFYQiqy+Tpj7Ef7dRRS6+YHtpdf8uFxTAG6iIraCaXspgexuqpsA4ynccRhrKGoMAnfcSGrshOTLx28kNUlEZ4CEEx5DC/vPkeOQj/KvfPrOPfbJGzB8LmWn64lunfuzcOw9d4rPDny9ePBY09b3y2CRpOJSHfGholsxatERQQLot35U6bUVzm0iz5YMvtk+/h45i9Ae+b4Ob4LOR9B6z1PXlCNO3J7yK0Nhl+RIJBmbyybJAxnWofqa88EzF4p+e8KyPZiZNAONZ3fdZ6J11YJ1fVGawxltJ6sFDT0w9Il1tmhsT559RMlfy/iGDRNjckGLCah+OpS75bfvXm/LqAAvQLBNVwtEcOx04twS8SwXq80F3FIbuem8Dzhu/7izcBUgclVE8Z2XP0W8DKbDkLiPadCx1vmL00DYrC/bZMqM5XoxhO0/c+c=
