language: bash

addons:
  sonarcloud:
    organization: "enescinar914"
    token: $SONAR_TOKEN
    
install: chmod u+x test.sh

script: 
  - bash test.sh
  - sonar-scanner

deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: "sm703bucket"
  region: us-east-2
  skip_cleanup: true
  on:
    branch: main
