language: bash
install: chmod u+x test.sh
script: bash test.sh
#Change on bucket permission
deploy:
  provider: s3
  access_key_id:
    secure: R9Fp0efIVY68wTd/mFLOoAgQiGwRgdaoNYT+7sivNskyq6y+cbdhbBkk6fERpi5j2XKCjcHIAF83XBgishw9TzsSE6UxO7FeOCZnJvYb8mIZnW6eVKNRfj0F/vlG7clnPVAPi+Jnnv6zZ0ENu50LMW0Yj87p/kCgqVc/HlhzNjHTiCN77WQOHet96Xuo2UJpYE8engM+nVRRcQ3OE71oQuMfdpxXrPntvwQP6ghDiyNL1v5JU+Z0Ee4qbozrF8dlR6ZT0PoXJsi9lFZreIgiaHXzZjvxribRppHgvJhQbEnQ6mPQjc5YqorTrc2fNlx/hDDE7Y5qQwp6n0VqQFg5gRYyKpVZCRhFTkk2zREqitOVlYcqjnK9iZylUYCKXD43IJUbFD/W48R2dRSmNPzobbFXH95m5p271inSPTaxIJPsZ8ZKSN5OVGYhfkJP0HQd/HKpDF3rqV6tWA7ZMaXvltA4tUSEbgVJ4zsrDpmFDDsKJZ9klWSAhI7etni4K76l+y8N8z2m65/Iq9t0CEzwBcuhvs+uiPcC2dHFlfuZyf9LioTavo3stOzppEfYx4v0WXnfxthJFFfJsC042sWy8hCxkY1lQ0bwcAkF4/rEaDj8fdTRuQJpoaDdc7L4c3+cm16hDCNG8WZ0w1ItbfJyrf25eUyUNv6yHiiCURXS+SQ=
  secret_access_key:
    secure: LIhzIrOoDSxJsXuiif7wUA4avlvxag3U45nyaAqkqjfWM1HE3u9eaCHiM+xS0L+xPBryLM59Mco/HCzY//EB1RjZ9ylsUpCM5PKdeB18nyFLza8ca8HGHS+Wv7a4q3zw72/nfSV5dgeoK+KBs2IiAU3zc7wZVNjL99j1zQeMZkhcyHA9q+KeGPofyYQftiPwL67CeywD29xXzoRfKtxJHzLp+Q6yrntNeIpOB5t4l/LH+5IqNW7w06yDtDI4SsiRd6ch7JBFQlV0nRzNSkpAO3gZ9P0h3cWzbJViix4jEyeygnBtX0fgad5LV/0TkJ/BnHApRUs3R3LJZnrkh9d2u5HFTr7NYjmkIlW/EGaawt3osdI45xS+tL4HezehHiV0dsFaneSh5kVL8SRF7+DNrNjgAEXJP7norQDH9YY4+/Zg5QceiJy/AlNOhAvfoK17LsCdhx0G0WEahkrRuvqlDtZxCJNkUT86i8amXhR9IGlHIMwi/8GlbNmizq/LNnItQtkoKlqMfdfRIgRE8mePN9NtfabFhkdP9x4r5KXkQHI/FtPFs4AK8WH1ka7tsVTnPfxQobaoW7IX0xCXC4varsE4rYWuAjwT//5z53KUFGLEx2BAGbxh/vcAF/0ss1AUpsWp2qsMh/8xi3UhYqtiQ8B8xrmCNsrsLdLUKXyNTUo=
  bucket: "sm703bucket"
  skip_cleanup: true
  on:
    branch: main
