# Set the language
language: bash

# Grant permission to a file
install: chmod u+x test.sh

# Main test script
script: bash test.sh

# Deployment phase
deploy:
  provider: s3
  access_key_id:
    secure: "SM69iUykSeH3ettsaT7clr9YHlQ01KKo95Z/f1d4NKMJFeyJ0J8qKEnHFYsNR+pPU7lsyOx9yEJvQvnZt9uc/e7MQZOaM0Q/JHvpl+yO7Bll2iWpm2Dv3bcAVLJuTIF6mk8N40yjqSARbRrjlIK/NYV2j8nPaLCqPD039ZRBRBItXMmsUrQwTtGGgDy16GIrfafeq4P8sH2tnYJQvXm3CGV5QKT7M4ZCu4L0jqeM27yJ3+V/fwVyyRrPI+7ZAMSf/0D1flD7BL9qeGlpifg0egiBxYdT5/dnULXNizKdlM316sruiPY65mS0CAkeWFVdC/9pApfbSPFm/x+KbCurQocWQ+dtoolAVL7aJJOb7/FE+UcH5QHnesKQAqh8ozJwL+n0NqP7tfJ9bxU0qbfOqH2Vl81RHL1GpskneOgZjdfllLa5KiWSJIqJkBjbYrTg7KfUobZaNPtGzKryBqnoF0GUdb5D8LdgfQsz5mJjrC8/UaUZPap6ECZGpVVepjb1ZxkvRsHZ3VWxCHYon7swctHxnzgcaxsVx2C796IsQDcyo3KaeucxfEPG4TLSY/j20PKMKMA+yn+J5+ipLx9Ozi03sVtnKMvYF9SbueR+ESi0R03I7+DbhJLsTJ+KWHfvSqv3geIWROEcEUMo7Rynid9DIx82ioySxgKJVOusP4E="
  secret_access_key:
    secure: "VypQwmh6dqflOadY7eZN24dE9rAXVWK5B4EMW9bUbL6Kqm4tcqT7wzs4rm5tbQf/9xvl+wxAE/FRVGfK3uAgoRUNpxOWkxN1vSBzZ86sq3z6XElgditfdrp/wflLCtBIdF5XhmZVBm56VEpzecHnqjdMh8+FOtUXV1QLHXZwA+MHlOCgvDonJgy2RT4Bg8nHPpMkVhpu9Qc0SIoBRqTviJjqDXIewpoHoFVFKikfIXWxdeVjhIfS8PfoMa/BBKVLnX4/sHE/qKYfxRqJSfDMHqHvVhtxeWeUr/bejFCEgL4jSm27fOyAtyY3Ru2/B3iAmCAvkZt2FhUxNgCqDArTKf0+rWY71Luu9ySR7by2Wo87CblUJ0YkZoqGqLgchqPLQuNg4xuIohf2UTu0WAHkl6W1gJN1pZb5NiNABB5sDe0iEmZ3sK0hrSDCtTA0JWVzc9I6V+GjSFHyk6jYJ7N6M2ePaiyp/PfXYltnFhNJUxFmYYIdYIWtFnZZuqvqDqfNQT89jRwFreAB5QOXR9MxGk+SvLTTn9Fn3TVcmdAz7fEKRoKAkE3jXnEtKvfMwHCU78qEzfy0rmyAfeiqCbIN1fltikNtOg+5nqM+de+fF0m3+92K7QUUvMAJs96hp3yMLlWfLvDDZubkzWFkaqD4zBNHt6BEb/mAOQZAorTy2qo="
  bucket: "sm703bucket"
