os: linux
dist: bionic 
language: java
jdk: openjdk11

if: branch IN (main, development, qa)

addons:
  sonarcloud:
    organization: "enescinar914"
    token: $SONAR_TOKEN
    
before_install: 
  - java --version
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.8.8/terraform_0.8.8_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"
  
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=enescinar914_sm703
  - AWS_DEFAULT_REGION='us-east-2' terraform plan ./terraform

after_script:
  - sonar-scanner

deploy:
  - provider: script
    skip_cleanup: true
    script: terraform apply ./terraform
    on:
      branch: main
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: "sm703bucket"
    region: us-east-2
    skip_cleanup: true
    on:
      branch: main
    
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: "developmentsm703"
    region: us-east-2
    skip_cleanup: true
    on:
      branch: development
    
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: "qasm703"
    region: us-east-2
    skip_cleanup: true
    on:
      branch: qa
    
notifications:
  email: 
    recipients:
      - enescinar944@gmail.com
    on_success: always
    on_failure: always
