language: bash
install: chmod u+x test.sh
script: bash test.sh
#Change on bucket permission
deploy:
  provider: s3
  access_key_id:
    secure: "Bz6yUnOB2edbUGpLtcSPiHZR5/RgOsAIuizW6jh9T3+qaSws/bDToDzL/FyrlTs5GE/9cPX9dEOFyzR9dndq6PPVce7a2Dshek1H5Bsed/iqd8QxYKLTkcgJvN/sb2eoIpXpKqdFEc88XLDtxk1u1DAwSGqoPXbic8f+POF2iacvPgpH1SsCpk8bbmZY01IDmn3avgRwu++VMAX2blkJe4rb8VLpoMjE0+FxgqMcnl2wBM/TYpNepilREZhmD0qB9xNTF7Cz/tysI8DfGBqPQAjp11aXqfbLmV/7+fglZsTfj3F5+TyG/9nS7dU9ROYucBlFQoTOCT7v/7BWzy0DJ+dxCCX4SAqNrWG4NOlwV6sDdV3nN6Tke5KBwmxRn8CA5IQnSmQ4pfC8JRVx7mpD+KAlYYMKpVE9n/8OLyzhsDOdMXjA8pX2z2z943NjsQsIv9CR8ocOIxP2DcQNRiT8JqBSqnnaKmyIR+SpEQ5KpxnmF6ro+kVthTmwz8yN8etWeeobP8el4JjICXII90+QN5VuQweYCDOhPiyC7IfLt7b/c4h8m1tl7H5BE/159MS0OPLHlTxZc82nJ05Ej8j4p1eo8vu8BvKNY+jqdQBzHYcxFDwAiAzdXWzCJvAhds7eajKX/zlIBnSUzn2ff3Nr8bgcw2LzWARvpWJljSZj1es="
  secret_access_key:
    secure: "Jvb/T1XuQVX2fVsi7K45YFB/JwPgfe0D/FTKaAvfhdDNWdQ72uNAYDl6x36lZlzs2PPmvKOT29W7hnKKMvlNkqppbUt9UjiVU7PxJXRHKummrmQZLHsPlCay0NOwJQmEKyj7r+NnI61D6cS0Vu1/V1evtVXJzcm7ewkIGxRwf1pq+H2NevmF3M27TWplbrNZ6lxgUU3Z9RHS9UavufezwhOjM5zuFCuQzXFVyJPprfWvNy2QrNp1NeuM7KSTPkDTRUFdAuF17GcPkvyRSrH4esEvmdp75NxgvCvUAC4zU3feIaZe3RTgq135QS6jcn+6LJ4DuopKVeLJS3kxVQcEIPSXnQs3i+JhKg0UOjPEVyyRsVzahxHujoG+Eypj6TPoKmI8Y+oj+KdAVaWB2ck+2ra7UWGx8ze2QHLYQP+780qaRiDaJU+nUumUriNlm8FNeht6e9N8GqlH0X3i1IAbbq+DumpgsISEYnON9RA9dC/bHjYZjM1DDFjsdxByt5wu5S5rJt72CWM81bfqsOycrC+CUbdXPCVqJmZwlYP1EkdjeG1alorpETcLlGjZ1dyc0ih4IsenaUjhLJsGl+2VmsxE7tZ+Hb5GBsypVssP4ZKfxQE/RRjc5mrRITe0HW++wcOrDR2Xt6qMT9cSDkNrnjDleYeTAOtthrj2S6A9Kx0="
  bucket: "sm703bucket"
  skip_cleanup: true
  region: us-east-2
  on:
    branch: main
